sap.ui.require.preload({
	"ui5lab/app/GeometryApp/Component.js":function(){sap.ui.define(["sap/ui/core/UIComponent","sap/ui/Device","ui5lab/app/GeometryApp/model/models","sap/ui/core/ComponentSupport"],function(e,t,p){"use strict";return e.extend("ui5lab.app.GeometryApp.Component",{metadata:{manifest:"json"},init:function(){e.prototype.init.apply(this,arguments);this.setModel(p.createDeviceModel(),"device")}})});
},
	"ui5lab/app/GeometryApp/controller/App.controller.js":function(){sap.ui.define(["sap/ui/core/mvc/Controller","sap/ui/model/json/JSONModel"],function(e,i){"use strict";return e.extend("ui5lab.app.GeometryApp.controller.App",{onInit:function(){var e=new i({size:200});this.getView().setModel(e,"view")}})});
},
	"ui5lab/app/GeometryApp/i18n/i18n.properties":'title=Square App\r\nappTitle=Square App\r\nappDescription=An app that displays a square - wow!',
	"ui5lab/app/GeometryApp/manifest.json":'{"_version":"1.5.0","sap.app":{"id":"ui5lab.app.GeometryApp","type":"application","i18n":"i18n/i18n.properties","applicationVersion":{"version":"1.0.0"},"title":"{{appTitle}}","description":"{{appDescription}}","resources":"resources.json","ach":"ach","sourceTemplate":{"id":"ui5template.basicSAPUI5ApplicationProject","version":"1.40.12"}},"sap.ui":{"technology":"UI5","icons":{"icon":"","favIcon":"","phone":"","phone@2":"","tablet":"","tablet@2":""},"deviceTypes":{"desktop":true,"tablet":true,"phone":true},"supportedThemes":["sap_hcb","sap_belize"]},"sap.ui5":{"rootView":{"viewName":"ui5lab.app.GeometryApp.view.App","type":"XML"},"dependencies":{"minUI5Version":"1.60.0","libs":{"sap.ui.core":{},"sap.m":{},"ui5lab.geometry":{}}},"contentDensities":{"compact":true,"cozy":true},"models":{"i18n":{"type":"sap.ui.model.resource.ResourceModel","settings":{"bundleName":"ui5lab.app.GeometryApp.i18n.i18n"}}},"resources":{"css":[{"uri":"https://rawgit.com/openui5/UI5Lab-control-simple/master/src/ui5lab/control/Square.css"}]}}}',
	"ui5lab/app/GeometryApp/model/models.js":function(){sap.ui.define(["sap/ui/model/json/JSONModel","sap/ui/Device"],function(e,n){"use strict";return{createDeviceModel:function(){var i=new e(n);i.setDefaultBindingMode("OneWay");return i}}});
},
	"ui5lab/app/GeometryApp/view/App.view.xml":'<mvc:View\r\n\tcontrollerName="ui5lab.app.GeometryApp.controller.App"\r\n\txmlns:mvc="sap.ui.core.mvc"\r\n\txmlns:lab="ui5lab.geometry"\r\n\txmlns="sap.m"><Shell><App><pages><Page title="{i18n>title}"><content><Slider value="{view>/size}" min="50" max="500"/><lab:Square text="A" size="100"/><lab:Square text="wonderful" size="{view>/size}"/><lab:Square text="pile" size="80"/><lab:Square text="of" size="140"/><lab:Square text="custom" size="90"/><lab:Square text="Squares" size="170"/><lab:Square text="!" size="50"/><lab:Circle text="Circle" size="{view>/size}"/><lab:Triangle text="Triangle" size="{view>/size}" rotation="{= Math.round(${view>/size} / 2 - 100)}"/></content></Page></pages></App></Shell></mvc:View>'
});
